FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app
COPY ./migrations ./migrations
COPY alembic.ini .


RUN adduser --disabled-password --gecos "" appuser

EXPOSE 8080 
# Documenting the port Gunicorn will listen on (via $PORT)

# ENTRYPOINT ["./debug_entrypoint.sh"] # Using CMD is also fine for this script