"""add desc field to codingproblem4

Revision ID: 198a1c6d8478
Revises: a4a71094fbd8
Create Date: 2025-04-27 01:12:50.763426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '198a1c6d8478'
down_revision: Union[str, None] = 'a4a71094fbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coding_problems')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_problems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('example_cases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('test_cases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('starter_code', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='coding_problems_pkey'),
    sa.UniqueConstraint('slug', name='coding_problems_slug_key')
    )
    # ### end Alembic commands ###
