"""add codingProblem table

Revision ID: 2adf88f4cedc
Revises: f87f8d7ffe4b
Create Date: 2025-04-26 00:24:17.597203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adf88f4cedc'
down_revision: Union[str, None] = 'f87f8d7ffe4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
