"""add example input

Revision ID: 7b7c844a73f9
Revises: 555a7c97a63a
Create Date: 2025-05-06 10:47:12.270126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7c844a73f9'
down_revision: Union[str, None] = '555a7c97a63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_problems', sa.Column('example_input', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coding_problems', 'example_input')
    # ### end Alembic commands ###
