"""make chat user_id non-nullable

Every write path already sets user_id (see app/routes/chat.py), so the nullable
columns only ever allowed orphaned rows that the app itself could not produce.

This will fail loudly if any pre-existing row has a NULL user_id, which is the
correct behaviour — those rows belong to no one and silently deleting or
reassigning them would be worse than stopping. Checked before writing this: Neon
had 1 chat_sessions row and 0 chat_messages rows, with zero NULLs in either.

Revision ID: dcf235f97791
Revises: ab8baf0c14ff
Create Date: 2026-08-26 20:36:23.788242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf235f97791'
down_revision: Union[str, None] = 'ab8baf0c14ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
