"""add user id to chatmessage

Revision ID: f87f8d7ffe4b
Revises: 4ba4db1742f4
Create Date: 2025-04-25 21:29:17.074122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87f8d7ffe4b'
down_revision: Union[str, None] = '4ba4db1742f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'user_id')
    # ### end Alembic commands ###
