name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'devdash/backend/**'
      - '.github/workflows/deploy_backend.yml'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Generate deployment package
        run: |
          mkdir -p deploy/
          cp -r devdash/backend deploy/backend
          
          # Check if .ebextensions directory exists before copying
          if [ -d "devdash/.ebextensions" ]; then
            cp -r devdash/.ebextensions deploy/
          else
            mkdir -p deploy/.ebextensions
          fi
          
          # Check if .platform directory exists before copying
          if [ -d "devdash/.platform" ]; then
            cp -r devdash/.platform deploy/
          else
            mkdir -p deploy/.platform
          fi
          
          cp devdash/backend/application.py deploy/
          cp devdash/backend/requirements.txt deploy/
          
          # Create or update security group config to use ID instead of name
          cat > deploy/.ebextensions/securitygroup.config << 'EOF'
          option_settings:
            aws:autoscaling:launchconfiguration:
              SecurityGroups: ${{ secrets.EB_SECURITY_GROUP_ID }}
          EOF
          
          # Add debug script
          mkdir -p deploy/.platform/hooks/postdeploy
          cat > deploy/.platform/hooks/postdeploy/01_debug.sh << 'EOF'
          #!/bin/bash
          echo "Environment variables available:" > /var/log/deploy-debug.log
          env | grep -v KEY | grep -v SECRET >> /var/log/deploy-debug.log
          echo "Files in app directory:" >> /var/log/deploy-debug.log
          find /var/app -type f -name "*.py" | sort >> /var/log/deploy-debug.log
          chmod 644 /var/log/deploy-debug.log
          EOF
          chmod +x deploy/.platform/hooks/postdeploy/01_debug.sh
          
          cd deploy
          zip -r ../deploy.zip .
          cd ..
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: DevDashBackend
          environment_name: DevDashBackend-env
          version_label: backend-${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_deployment: true