name: Deploy Frontend to AWS Amplify

on:
  push:
    branches:
      - main
    paths:
      - 'devdash/frontend/**'
      - '.github/workflows/deploy_frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd devdash/frontend
          npm ci
          
      - name: Build frontend
        run: |
          cd devdash/frontend
          # Create production build with the correct API URL
          VITE_API_URL=${{ secrets.BACKEND_API_URL }} npm run build
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          

      # Alternatively, if using AWS Amplify, use their GitHub Actions
      - name: Deploy to AWS Amplify
        uses: aws-amplify/amplify-cli-action@master
        with:
           amplify_command: publish
           amplify_env: production
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: ${{ secrets.AWS_REGION }}