name: Deploy Frontend to AWS S3 and CloudFront

on:
  push:
    branches:
      - main # Or your primary deployment branch
    paths:
      - './devdash/frontend/**' # Trigger on changes within the frontend directory
      - '.github/workflows/deploy-frontend.yml' # Trigger if this workflow file itself changes

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.APP_RUNNER_BACKEND_URL_WITH_API_PREFIX }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies and Build
        # CORRECTED: The working directory needs to point to where your frontend's package.json is
        working-directory: ./devdash/frontend 
        run: |
          echo "Using VITE_API_BASE_URL: $VITE_API_BASE_URL"
          npm ci
          npm run build

      - name: Deploy to S3
        run: |
          # The sync command needs the correct path to the 'dist' folder after building
          aws s3 sync ./devdash/frontend/dist s3://${{ secrets.S3_BUCKET_NAME }}/ --delete
          # I have removed '--acl public-read' as it's generally not needed when using CloudFront with OAC.
          # Your S3 bucket policy should be what grants CloudFront access.

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFONT_DISTRIBUTION_ID }}