name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'devdash/backend/**'
      - '.github/workflows/deploy_backend.yml'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Generate deployment package
        run: |
          mkdir -p deploy/
          
          # Core application files
          cp -r devdash/backend deploy/backend
          cp devdash/backend/application.py deploy/
          cp devdash/backend/requirements.txt deploy/
          
          # Copy .ebextensions and .platform directories properly
          if [ -d "devdash/.ebextensions" ]; then
            cp -r devdash/.ebextensions deploy/
          else
            mkdir -p deploy/.ebextensions
          fi
          
          if [ -d "devdash/.platform" ]; then
            cp -r devdash/.platform deploy/
          else
            mkdir -p deploy/.platform
          fi
          
          # IMPORTANT: Create a backup of the original environment.config
          if [ -f "deploy/.ebextensions/01_environment.config" ]; then
            cp deploy/.ebextensions/01_environment.config deploy/.ebextensions/01_environment.config.bak
          fi
          
          # Create a simplified environment.config without VPC settings
          cat > deploy/.ebextensions/01_environment.config << 'EOF'
          option_settings:
            aws:elasticbeanstalk:application:environment:
              ENVIRONMENT: production
              DEBUG: false
              PYTHONPATH: /var/app/venv/staging-LQM1lest/bin
            
            aws:elasticbeanstalk:environment:
              ServiceRole: aws-elasticbeanstalk-service-role
              LoadBalancerType: application
            
            aws:elasticbeanstalk:healthreporting:system:
              SystemType: enhanced
          EOF
          
          cd deploy
          zip -r ../deploy.zip .
          cd ..
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: DevDashBackend
          environment_name: DevDashBackend-env
          version_label: backend-${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_deployment: true
          use_existing_version_if_available: true