name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'devdash/backend/**'
      - '.github/workflows/deploy_backend.yml'
env:
  ACTIONS_STEP_DEBUG: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Generate deployment package
        run: |
          # Create a temporary directory for restructuring
          mkdir -p deploy/
          
          # Copy backend code
          cp -r devdash/backend deploy/backend
          
          # Copy deployment configuration
          cp -r devdash/.ebextensions deploy/
          cp -r devdash/.platform deploy/
          
          # Copy or create application entry point
          cp devdash/backend/application.py deploy/
          
          # Copy requirements
          cp devdash/backend/requirements.txt deploy/
          
          # Create deployment zip from the prepared directory
          cd deploy
          zip -r ../deploy.zip .
          cd ..
          
          echo "Created deployment package"
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: DevDashBackend
          environment_name: DevDashBackend-env
          version_label: backend-${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_deployment: true