name: Deploy Frontend to AWS Amplify

on:
  push:
    branches:
      - main
    paths:
      - 'devdash/frontend/**'
      - '.github/workflows/deploy_frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd devdash/frontend
          npm ci
          
      - name: Build frontend
        run: |
          cd devdash/frontend
          # Create a .env file for the build
          echo "VITE_API_URL=${{ secrets.BACKEND_API_URL }}" > .env
          npm run build
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          

      # Alternatively, if using AWS Amplify, use their GitHub Actions
      - name: Deploy to AWS Amplify
        run: |
          # Install AWS Amplify CLI
          npm install -g @aws-amplify/cli
          
          # Deploy to Amplify - Method 1: If you have an existing Amplify app
          # Extract your Amplify App ID from the AWS Console or store it as a GitHub secret
          AMPLIFY_APP_ID=${{ secrets.AMPLIFY_APP_ID }}
          aws amplify start-deployment --app-id $AMPLIFY_APP_ID --branch-name main --source-url ${{ github.server_url }}/${{ github.repository }}/archive/refs/heads/main.zip
